In [1]:
# Q1.1: Create a 4x4 identity matrix using np.eye()

import numpy as np

x= np.eye(4,4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
# Q1.2: Create an array of 8 zeros using np.zeros()

x= np.zeros(8)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
# Q1.3: Create an array of 6 ones using np.ones()

x= np.ones(6)
print(x)

[1. 1. 1. 1. 1. 1.]


In [6]:
# Q1.4: Create an array with values from 0 to 15 using np.arange()
x= np.arange(0,15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [7]:
# Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()

x= np.linspace(0,100,8)
print(x)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [23]:
# The assignment uses banking industry data with 10 rows × 5 columns:

# Customer_ID: Unique identifier for each customer
# Account_Balance: Customer's account balance in dollars
# Credit_Score: Customer's credit score (300-900 range)
# Transaction_Count: Number of transactions in the last month
# Years_Active: Number of years the customer has been with the bank

banking_data= np.array([[111,2989.5,500,10,5],
                        [222,4000.1,600,6,15],
                        [444,900.9,900,8,5],
                        [333,5000,800,13,18],
                        [777,5848.8,700,25,20],
                        [888,4893.5,850,16,10],
                        [555,6798.2,600,6,17],
                        [000,4886.2,400,10,22],
                        [999,9876.2,500,12,2],
                        [666,3003.6,800,22,30]   
                        ])


np.set_printoptions(suppress=True, precision=2)
print(banking_data)

[[ 111.  2989.5  500.    10.     5. ]
 [ 222.  4000.1  600.     6.    15. ]
 [ 444.   900.9  900.     8.     5. ]
 [ 333.  5000.   800.    13.    18. ]
 [ 777.  5848.8  700.    25.    20. ]
 [ 888.  4893.5  850.    16.    10. ]
 [ 555.  6798.2  600.     6.    17. ]
 [   0.  4886.2  400.    10.    22. ]
 [ 999.  9876.2  500.    12.     2. ]
 [ 666.  3003.6  800.    22.    30. ]]


In [3]:
# Q2.1: What is the shape of the banking_data array?
import numpy as np
banking_data= np.array([[111,2989.5,500,10,5],
                        [222,4000.1,600,6,15],
                        [444,900.9,900,8,5],
                        [333,5000,800,13,18],
                        [777,5848.8,700,25,20],
                        [888,4893.5,850,16,10],
                        [555,6798.2,600,6,17],
                        [000,4886.2,400,10,22],
                        [999,9876.2,500,12,2],
                        [666,3003.6,800,22,30]   
                        ])


np.set_printoptions(suppress=True, precision=2)

print(banking_data.shape)

(10, 5)


In [4]:
# Q2.2: What is the data type of the banking_data array?
banking_data.dtype

dtype('float64')

In [6]:
# Q2.3: What is the size (total number of elements) of the banking_data array?
print(banking_data.size)

50


In [7]:
# Q2.4: What is the number of dimensions of the banking_data array?
print(banking_data.ndim)

2


In [8]:
# Q2.5: What is the memory size of the banking_data array in bytes?
print(banking_data.nbytes)

400


In [10]:
# Q3.1: Extract the first row of banking_data
print(banking_data[0,:])

[ 111.  2989.5  500.    10.     5. ]


In [11]:
# Q3.2: Extract the last row of banking_data
print(banking_data[9,:])

[ 666.  3003.6  800.    22.    30. ]


In [12]:
# Q3.3: Extract the Account_Balance column (column index 1)
print(banking_data[:,1])

[2989.5 4000.1  900.9 5000.  5848.8 4893.5 6798.2 4886.2 9876.2 3003.6]


In [13]:
# Q3.4: Extract the first 4 rows and first 3 columns
print(banking_data[0:4,0:3])

[[ 111.  2989.5  500. ]
 [ 222.  4000.1  600. ]
 [ 444.   900.9  900. ]
 [ 333.  5000.   800. ]]


In [ ]:
# Q3.5: Extract rows 3 to 7 (inclusive)
banking_data= np.array([[111,2989.5,500,10,5],
                        [222,4000.1,600,6,15],
                        [444,900.9,900,8,5],
                        [333,5000,800,13,18],
                        [777,5848.8,700,25,20],
                        [888,4893.5,850,16,10],
                        [555,6798.2,600,6,17],
                        [000,4886.2,400,10,22],
                        [999,9876.2,500,12,2],
                        [666,3003.6,800,22,30]   
                        ])
print(banking_data[2:7,:])

[[ 444.   900.9  900.     8.     5. ]
 [ 333.  5000.   800.    13.    18. ]
 [ 777.  5848.8  700.    25.    20. ]
 [ 888.  4893.5  850.    16.    10. ]
 [ 555.  6798.2  600.     6.    17. ]]


In [16]:
# Q4.1: Calculate the sum of all account balances
x= np.sum(banking_data[:,1])
print(x)

48196.99999999999


In [18]:
# Q4.2: Calculate the mean account balance
x= np.mean(banking_data[:,1])
print(x)

4819.699999999999


In [20]:
# Q4.3: Calculate the standard deviation of account balances
x= np.std(banking_data[:,1])
print(x)

2307.8272669331213


In [22]:
# Q4.4: Calculate the variance of account balances
x= np.var(banking_data[:,1])
print(x)

5326066.694


In [23]:
# Q4.5: Calculate the median account balance
x= np.median(banking_data[:,1])
print(x)

4889.85


In [24]:
# Q5.1: Find the minimum and maximum account balances
x= np.max(banking_data[:,1])
y= np.min(banking_data[:,1])
print(x), print(y)

9876.2
900.9


(None, None)

In [25]:
# Q5.2: Find the minimum and maximum credit scores
x= np.max(banking_data[:,2])
y= np.min(banking_data[:,2])
print(x), print(y)

900.0
400.0


(None, None)

In [28]:
# Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
p25= np.percentile(banking_data[:,1],25)
p50= np.percentile(banking_data[:,1],50)
p75= np.percentile(banking_data[:,1],75)

print(p25), print(p50), print(p75)

3252.725
4889.85
5636.6


(None, None, None)

In [29]:
# Q5.4: Calculate the correlation between account balance and credit score
banking_data= np.array([[111,2989.5,500,10,5],
                        [222,4000.1,600,6,15],
                        [444,900.9,900,8,5],
                        [333,5000,800,13,18],
                        [777,5848.8,700,25,20],
                        [888,4893.5,850,16,10],
                        [555,6798.2,600,6,17],
                        [000,4886.2,400,10,22],
                        [999,9876.2,500,12,2],
                        [666,3003.6,800,22,30]   
                        ])

x= np.corrcoef(banking_data[:,1], banking_data[:,2])[0,1]
print(x)

-0.46128061366331713


In [30]:
# Q5.5: Calculate the covariance between account balance and credit score
x= np.cov(banking_data[:,1],banking_data[:,2])[0,1]
print(x)

-190818.88888888888


In [31]:
print(banking_data)

[[ 111.  2989.5  500.    10.     5. ]
 [ 222.  4000.1  600.     6.    15. ]
 [ 444.   900.9  900.     8.     5. ]
 [ 333.  5000.   800.    13.    18. ]
 [ 777.  5848.8  700.    25.    20. ]
 [ 888.  4893.5  850.    16.    10. ]
 [ 555.  6798.2  600.     6.    17. ]
 [   0.  4886.2  400.    10.    22. ]
 [ 999.  9876.2  500.    12.     2. ]
 [ 666.  3003.6  800.    22.    30. ]]


In [32]:
import numpy as np

# Your banking data
banking_data = np.array([
    [111.,  2989.5, 500., 10., 5.],
    [222.,  4000.1, 600., 6., 15.],
    [444.,   900.9, 900., 8., 5.],
    [333.,  5000.,  800., 13., 18.],
    [777.,  5848.8, 700., 25., 20.],
    [888.,  4893.5, 850., 16., 10.],
    [555.,  6798.2, 600., 6., 17.],
    [0.,    4886.2, 400., 10., 22.],
    [999.,  9876.2, 500., 12., 2.],
    [666.,  3003.6, 800., 22., 30.]
])

# Calculate covariance between account balance (col 1) and credit score (col 2)
covariance = np.cov(banking_data[:, 1], banking_data[:, 2])[0, 1]
print("Covariance between account balance and credit score:", covariance)


Covariance between account balance and credit score: -190818.88888888888


In [33]:
# Q6.1: Reshape the banking_data to 5 rows × 10 columns
x= banking_data.reshape(5,10)
print(x)

[[ 111.  2989.5  500.    10.     5.   222.  4000.1  600.     6.    15. ]
 [ 444.   900.9  900.     8.     5.   333.  5000.   800.    13.    18. ]
 [ 777.  5848.8  700.    25.    20.   888.  4893.5  850.    16.    10. ]
 [ 555.  6798.2  600.     6.    17.     0.  4886.2  400.    10.    22. ]
 [ 999.  9876.2  500.    12.     2.   666.  3003.6  800.    22.    30. ]]


In [34]:
# Q6.2: Flatten the banking_data to a 1D array
print(banking_data.flatten())

[ 111.  2989.5  500.    10.     5.   222.  4000.1  600.     6.    15.
  444.   900.9  900.     8.     5.   333.  5000.   800.    13.    18.
  777.  5848.8  700.    25.    20.   888.  4893.5  850.    16.    10.
  555.  6798.2  600.     6.    17.     0.  4886.2  400.    10.    22.
  999.  9876.2  500.    12.     2.   666.  3003.6  800.    22.    30. ]


In [35]:
# Q6.3: Transpose the banking_data
banking_data.T

array([[ 111. ,  222. ,  444. ,  333. ,  777. ,  888. ,  555. ,    0. ,
         999. ,  666. ],
       [2989.5, 4000.1,  900.9, 5000. , 5848.8, 4893.5, 6798.2, 4886.2,
        9876.2, 3003.6],
       [ 500. ,  600. ,  900. ,  800. ,  700. ,  850. ,  600. ,  400. ,
         500. ,  800. ],
       [  10. ,    6. ,    8. ,   13. ,   25. ,   16. ,    6. ,   10. ,
          12. ,   22. ],
       [   5. ,   15. ,    5. ,   18. ,   20. ,   10. ,   17. ,   22. ,
           2. ,   30. ]])

In [40]:
# Q6.4: Split the banking_data into 2 equal parts vertically
x= np.vsplit(banking_data,2)
print(x)

[array([[ 111. , 2989.5,  500. ,   10. ,    5. ],
       [ 222. , 4000.1,  600. ,    6. ,   15. ],
       [ 444. ,  900.9,  900. ,    8. ,    5. ],
       [ 333. , 5000. ,  800. ,   13. ,   18. ],
       [ 777. , 5848.8,  700. ,   25. ,   20. ]]), array([[ 888. , 4893.5,  850. ,   16. ,   10. ],
       [ 555. , 6798.2,  600. ,    6. ,   17. ],
       [   0. , 4886.2,  400. ,   10. ,   22. ],
       [ 999. , 9876.2,  500. ,   12. ,    2. ],
       [ 666. , 3003.6,  800. ,   22. ,   30. ]])]


In [43]:
# Q6.5: Split the banking_data into 2 equal parts horizontally
x= np.hsplit(banking_data,5)
print(x)

[array([[111.],
       [222.],
       [444.],
       [333.],
       [777.],
       [888.],
       [555.],
       [  0.],
       [999.],
       [666.]]), array([[2989.5],
       [4000.1],
       [ 900.9],
       [5000. ],
       [5848.8],
       [4893.5],
       [6798.2],
       [4886.2],
       [9876.2],
       [3003.6]]), array([[500.],
       [600.],
       [900.],
       [800.],
       [700.],
       [850.],
       [600.],
       [400.],
       [500.],
       [800.]]), array([[10.],
       [ 6.],
       [ 8.],
       [13.],
       [25.],
       [16.],
       [ 6.],
       [10.],
       [12.],
       [22.]]), array([[ 5.],
       [15.],
       [ 5.],
       [18.],
       [20.],
       [10.],
       [17.],
       [22.],
       [ 2.],
       [30.]])]


In [ ]:
print(banking_data)
# Customer_ID: Unique identifier for each customer
# Account_Balance: Customer's account balance in dollars
# Credit_Score: Customer's credit score (300-900 range)
# Transaction_Count: Number of transactions in the last month
# Years_Active: Number of years the customer has been with the bank

[[ 111.  2989.5  500.    10.     5. ]
 [ 222.  4000.1  600.     6.    15. ]
 [ 444.   900.9  900.     8.     5. ]
 [ 333.  5000.   800.    13.    18. ]
 [ 777.  5848.8  700.    25.    20. ]
 [ 888.  4893.5  850.    16.    10. ]
 [ 555.  6798.2  600.     6.    17. ]
 [   0.  4886.2  400.    10.    22. ]
 [ 999.  9876.2  500.    12.     2. ]
 [ 666.  3003.6  800.    22.    30. ]]


In [50]:
# Q7.1: Find customers with account balance greater than $100,000
x=(banking_data[:,1]>100000)
print(banking_data[x])

[]


In [58]:
# Q7.2: Find customers with credit score greater than 800
Customer_ID= banking_data[:,0]
x= Customer_ID[banking_data[:,2]>800]
print(x)

[444. 888.]


In [57]:
# Extract customer IDs from column 0
Customer_ID = banking_data[:, 0]

# Get IDs of customers with credit score > 800 (from column 2)
x = Customer_ID[banking_data[:, 2] > 800]
print("Customer IDs with credit score > 800:", x)

Customer IDs with credit score > 800: [444. 888.]


In [ ]:

print(banking_data)
# Customer_ID: Unique identifier for each customer
# Account_Balance: Customer's account balance in dollars
# Credit_Score: Customer's credit score (300-900 range)
# Transaction_Count: Number of transactions in the last month
# Years_Active: Number of years the customer has been with the bank


[[ 111.  2989.5  500.    10.     5. ]
 [ 222.  4000.1  600.     6.    15. ]
 [ 444.   900.9  900.     8.     5. ]
 [ 333.  5000.   800.    13.    18. ]
 [ 777.  5848.8  700.    25.    20. ]
 [ 888.  4893.5  850.    16.    10. ]
 [ 555.  6798.2  600.     6.    17. ]
 [   0.  4886.2  400.    10.    22. ]
 [ 999.  9876.2  500.    12.     2. ]
 [ 666.  3003.6  800.    22.    30. ]]


In [65]:
# Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750
Transaction_Count=banking_data[:,3]
Credit_Score=banking_data[:,2]
Customers_ID=banking_data[:,0]
x= banking_data[(banking_data[:,3]>50) & (banking_data[:,2]<750)]
print(x)

[]


In [63]:
# Q7.4: Count how many customers have account balance between $10,000 and $100,000
count= np.sum((banking_data[:,1]>10000) & (banking_data[:,1]<100000))
print(count)

0


In [69]:
# Q7.5: Find the index of the customer with the highest credit score
x= np.argmax(banking_data[:,2])
print(x)

2


In [76]:
# Q8.1: Sort the banking_data by account balance (ascending)

x= banking_data[banking_data[:,1].argsort()]
print(x)

[[ 444.   900.9  900.     8.     5. ]
 [ 111.  2989.5  500.    10.     5. ]
 [ 666.  3003.6  800.    22.    30. ]
 [ 222.  4000.1  600.     6.    15. ]
 [   0.  4886.2  400.    10.    22. ]
 [ 888.  4893.5  850.    16.    10. ]
 [ 333.  5000.   800.    13.    18. ]
 [ 777.  5848.8  700.    25.    20. ]
 [ 555.  6798.2  600.     6.    17. ]
 [ 999.  9876.2  500.    12.     2. ]]


In [79]:
# Q8.2: Sort the banking_data by credit score (descending)

x= banking_data[banking_data[:,2].argsort()[::-1]]
print(x)

[[ 444.   900.9  900.     8.     5. ]
 [ 888.  4893.5  850.    16.    10. ]
 [ 333.  5000.   800.    13.    18. ]
 [ 666.  3003.6  800.    22.    30. ]
 [ 777.  5848.8  700.    25.    20. ]
 [ 222.  4000.1  600.     6.    15. ]
 [ 555.  6798.2  600.     6.    17. ]
 [ 999.  9876.2  500.    12.     2. ]
 [ 111.  2989.5  500.    10.     5. ]
 [   0.  4886.2  400.    10.    22. ]]


In [81]:
# Q8.3: Find the indices that would sort the array by years active
years_active= [banking_data[:,4].argsort()]
print(years_active)

[array([8, 0, 2, 5, 1, 6, 3, 4, 7, 9])]


In [90]:
# Q8.4: Find the customer with the second highest account balance

x=banking_data[:,1].argsort()[::-1][1]
print(x)


6


In [ ]:
print(banking_data)

[[ 111.  2989.5  500.    10.     5. ]
 [ 222.  4000.1  600.     6.    15. ]
 [ 444.   900.9  900.     8.     5. ]
 [ 333.  5000.   800.    13.    18. ]
 [ 777.  5848.8  700.    25.    20. ]
 [ 888.  4893.5  850.    16.    10. ]
 [ 555.  6798.2  600.     6.    17. ]
 [   0.  4886.2  400.    10.    22. ]
 [ 999.  9876.2  500.    12.     2. ]
 [ 666.  3003.6  800.    22.    30. ]]


In [6]:
# Q8.5: Find the customer with the lowest transaction count
# Your banking data
banking_data = np.array([
    [111.,  2989.5, 500., 10., 5.],
    [222.,  4000.1, 600., 6., 15.],
    [444.,   900.9, 900., 8., 5.],
    [333.,  5000.,  800., 13., 18.],
    [777.,  5848.8, 700., 25., 20.],
    [888.,  4893.5, 850., 16., 10.],
    [555.,  6798.2, 600., 6., 17.],
    [0.,    4886.2, 400., 10., 22.],
    [999.,  9876.2, 500., 12., 2.],
    [666.,  3003.6, 800., 22., 30.]
])

import numpy as np
lowest_count= np.argmin(banking_data[:,3])
x= banking_data[lowest_count]
print(x)

[ 222.  4000.1  600.     6.    15. ]


In [7]:
# Q9.1: Calculate the absolute values of all elements
x= np.abs(banking_data)
print(x)

[[1.1100e+02 2.9895e+03 5.0000e+02 1.0000e+01 5.0000e+00]
 [2.2200e+02 4.0001e+03 6.0000e+02 6.0000e+00 1.5000e+01]
 [4.4400e+02 9.0090e+02 9.0000e+02 8.0000e+00 5.0000e+00]
 [3.3300e+02 5.0000e+03 8.0000e+02 1.3000e+01 1.8000e+01]
 [7.7700e+02 5.8488e+03 7.0000e+02 2.5000e+01 2.0000e+01]
 [8.8800e+02 4.8935e+03 8.5000e+02 1.6000e+01 1.0000e+01]
 [5.5500e+02 6.7982e+03 6.0000e+02 6.0000e+00 1.7000e+01]
 [0.0000e+00 4.8862e+03 4.0000e+02 1.0000e+01 2.2000e+01]
 [9.9900e+02 9.8762e+03 5.0000e+02 1.2000e+01 2.0000e+00]
 [6.6600e+02 3.0036e+03 8.0000e+02 2.2000e+01 3.0000e+01]]


In [9]:
# Q9.2: Calculate the square root of all account balances
x= banking_data[:,1]**(1/2)
print(x)

[54.67632029 63.24634377 30.01499625 70.71067812 76.47744766 69.95355602
 82.45119769 69.90135907 99.37907224 54.80510925]


In [11]:
# Q9.3: Calculate the square of all credit scores
x= banking_data[:,2]**2
print(x)

[250000. 360000. 810000. 640000. 490000. 722500. 360000. 160000. 250000.
 640000.]


In [13]:
# Q9.4: Calculate the exponential of all transaction counts
x= np.exp(banking_data[:,3])
print(x)

[2.20264658e+04 4.03428793e+02 2.98095799e+03 4.42413392e+05
 7.20048993e+10 8.88611052e+06 4.03428793e+02 2.20264658e+04
 1.62754791e+05 3.58491285e+09]


In [14]:
# Q9.5: Calculate the natural logarithm of all account balances
x= np.log(banking_data[:,1])
print(x)

[8.00286143 8.29407464 6.80339426 8.51719319 8.67399179 8.49566307
 8.82441315 8.49417018 9.1978831  8.00756685]


In [16]:
# Q10.1: Calculate the cumulative sum of account balances
x= np.cumsum(banking_data[:,1])
print(x)

[ 2989.5  6989.6  7890.5 12890.5 18739.3 23632.8 30431.  35317.2 45193.4
 48197. ]


In [17]:
# Q10.2: Calculate the cumulative product of transaction counts
x= np.cumprod(banking_data[:,3])
print(x)

[1.000000e+01 6.000000e+01 4.800000e+02 6.240000e+03 1.560000e+05
 2.496000e+06 1.497600e+07 1.497600e+08 1.797120e+09 3.953664e+10]


In [19]:
# Q10.3: Calculate the difference between consecutive account balances
x= np.diff(banking_data[:,1])
print(x)

[ 1010.6 -3099.2  4099.1   848.8  -955.3  1904.7 -1912.   4990.  -6872.6]


In [20]:
# Q10.4: Calculate the gradient of account balances
x= np.gradient(banking_data[:,1])
print(x)

[ 1.01060e+03 -1.04430e+03  4.99950e+02  2.47395e+03 -5.32500e+01
  4.74700e+02 -3.65000e+00  1.53900e+03 -9.41300e+02 -6.87260e+03]


In [24]:
# Q10.5: Calculate the histogram of account balances with 5 bins
x,y= np.histogram(banking_data[:,1],bins=5)
print(x)
print(y)


[1 3 4 1 1]
[ 900.9  2695.96 4491.02 6286.08 8081.14 9876.2 ]


In [25]:
# Q11.1: Generate 6 random integers between 1 and 1000
x= np.random.randint(1,1001,6)
print(x)

[988 547 853 931 865 344]


In [26]:
# Q11.2: Generate 6 random floats between 0 and 1
r_floa= np.random.random(6)
print(r_floa)

[0.44178394 0.52652538 0.34428513 0.42358246 0.06720569 0.64739983]


In [28]:
# Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)
no_ = np.random.normal(700,100,6)
print(no_)

[760.95525101 650.093553   604.10270875 792.35687815 773.58178958
 721.56915954]


In [47]:
# Q11.4: Shuffle the banking_data rows randomly
x= banking_data.copy()

np.random.shuffle(x)
np.set_printoptions(suppress=True, precision=2)
print(x)


[[ 111.  2989.5  500.    10.     5. ]
 [ 222.  4000.1  600.     6.    15. ]
 [ 999.  9876.2  500.    12.     2. ]
 [ 888.  4893.5  850.    16.    10. ]
 [ 333.  5000.   800.    13.    18. ]
 [ 777.  5848.8  700.    25.    20. ]
 [   0.  4886.2  400.    10.    22. ]
 [ 666.  3003.6  800.    22.    30. ]
 [ 555.  6798.2  600.     6.    17. ]
 [ 444.   900.9  900.     8.     5. ]]


In [54]:
# Q11.5: Set random seed to 123 and generate 4 random numbers
x= np.random.randint(0,100,4)
np.random.seed(123)
cpy_of_x= x.copy()
np.random.shuffle(cpy_of_x)
print(cpy_of_x)

[17 66 92 98]


In [55]:
# Q12.1: Calculate the dot product of account balance and credit score columns
x= np.dot(banking_data[:,1],banking_data[:,2])
print(x)

30333635.0


In [58]:
# Q12.2: Calculate the cross product of first two rows
x= np.cross(banking_data[0,:3],banking_data[1,:3])
print(x)

[-206350.    44400.  -219657.9]


In [59]:
# Q12.3: Calculate the norm (magnitude) of the account balance column
x= np.linalg.norm(banking_data[:,1])
print(x)

16898.394830278998


In [63]:
# Q12.4: Create a 3x3 matrix and calculate its determinant
x= np.random.randint([[5,3],[3,4]])
print(x)
y= np.linalg.det(x)
print(y)

[[1 0]
 [1 2]]
2.0


In [65]:
# Q12.5: Calculate the inverse of the 3x3 matrix
x= np.random.randint(0,100,(3,3))
print(x)
y= np.linalg.inv(x)
print(y)

[[96 80 68]
 [49 55 67]
 [ 2 84 39]]
[[ 0.02 -0.01 -0.01]
 [ 0.01 -0.02  0.02]
 [-0.02  0.04 -0.01]]


In [66]:
# Q13.1: Convert all customer IDs to strings
import numpy as np
banking_data = np.array([
    [111.,  2989.5, 500., 10., 5.],
    [222.,  4000.1, 600., 6., 15.],
    [444.,   900.9, 900., 8., 5.],
    [333.,  5000.,  800., 13., 18.],
    [777.,  5848.8, 700., 25., 20.],
    [888.,  4893.5, 850., 16., 10.],
    [555.,  6798.2, 600., 6., 17.],
    [0.,    4886.2, 400., 10., 22.],
    [999.,  9876.2, 500., 12., 2.],
    [666.,  3003.6, 800., 22., 30.]
])

x= banking_data[:,0].astype(str)
print(x)


['111.0' '222.0' '444.0' '333.0' '777.0' '888.0' '555.0' '0.0' '999.0'
 '666.0']


In [71]:
# Q13.2: Check if any customer ID contains '100'

x= banking_data[:,0].astype(str)
y= np.char.find(x,'100')>=0
print(y)


[False False False False False False False False False False]


In [72]:
# Q13.3: Convert all customer IDs to uppercase (if they were strings)

x= banking_data[:,0].astype(str)
y= np.char.upper(x)
print(y)

['111.0' '222.0' '444.0' '333.0' '777.0' '888.0' '555.0' '0.0' '999.0'
 '666.0']


In [73]:
# Q13.4: Count the length of each customer ID string
x= banking_data[:,0].astype(str)
y= np.char.str_len(x)
print(y)

[5 5 5 5 5 5 5 3 5 5]


In [76]:
# Q13.5: Replace '100' with 'CUST' in customer IDs
x= banking_data[:,0].astype(str)
y= np.char.replace(x,"100","CUST")
print(y)

['111.0' '222.0' '444.0' '333.0' '777.0' '888.0' '555.0' '0.0' '999.0'
 '666.0']


In [77]:
# Q14.1: Convert years active to months
x= banking_data[:,4]
y=x*12

print(y)

[ 60. 180.  60. 216. 240. 120. 204. 264.  24. 360.]


In [78]:
# Q14.2: Calculate the average years active
x= banking_data[:,4]
y= np.mean(x)
print(y)

14.4


In [80]:
# Q14.3: Find customers who have been active for more than 5 years
x= banking_data[banking_data[:,4]>5]
print(x)


[[ 222.  4000.1  600.     6.    15. ]
 [ 333.  5000.   800.    13.    18. ]
 [ 777.  5848.8  700.    25.    20. ]
 [ 888.  4893.5  850.    16.    10. ]
 [ 555.  6798.2  600.     6.    17. ]
 [   0.  4886.2  400.    10.    22. ]
 [ 666.  3003.6  800.    22.    30. ]]


In [81]:
# Q14.4: Calculate the total time all customers have been active (in years)
x= np.sum(banking_data[:,4])
print(x)

144.0


In [82]:
# Q14.5: Find the customer with the shortest time active
x= np.min(banking_data[:,4])
print(x)

2.0


In [ ]:
# Q15.1: Apply a function to calculate 5% interest on all account balances

x= banking_data[:,1]*1.05
print(x)

# Q15.2: Use np.where to categorize customers by balance ranges
category= banking_data[:,1]
y= np.where(category<3000,"low","high")
print(y)

# Q15.3: Use np.select to categorize customers by credit score ranges

conditions = [
    banking_data[:, 2] < 500,
    (banking_data[:, 2] >= 500) & (banking_data[:, 2] < 700),
    banking_data[:, 2] >= 700
]
choices = ['Budget', 'Mid-range', 'Premium']
price_categories = np.select(conditions, choices, default='Unknown')
print(price_categories)



[ 3138.97  4200.11   945.95  5250.    6141.24  5138.18  7138.11  5130.51
 10370.01  3153.78]
['low' 'high' 'low' 'high' 'high' 'high' 'high' 'high' 'high' 'high']
['Mid-range' 'Mid-range' 'Premium' 'Premium' 'Premium' 'Premium'
 'Mid-range' 'Budget' 'Mid-range' 'Premium']


In [91]:
# Q15.4: Use np.piecewise to apply different interest rates based on balance

def low_price(x): return x * 0.9  # 10% discount
def mid_price(x): return x * 1.0  # No change
def high_price(x): return x * 1.1  # 10% markup

discounted_prices = np.piecewise(
    banking_data[:, 1],
    [banking_data[:, 1] < 20, (banking_data[:, 1] >= 20) & (banking_data[:, 1] < 50), banking_data[:, 1] >= 50],
    [low_price, mid_price, high_price]
)
print(discounted_prices)

# Q15.5: Use np.apply_along_axis to calculate the sum of each row\\

row_sums = np.apply_along_axis(np.sum, 1, banking_data)
print(row_sums)

[ 3288.45  4400.11   990.99  5500.    6433.68  5382.85  7478.02  5374.82
 10863.82  3303.96]
[ 3615.5  4843.1  2257.9  6164.   7370.8  6657.5  7976.2  5318.2 11389.2
  4521.6]
