In [1]:
# Q1.1: Create a 4x4 identity matrix using np.eye()

import numpy as np

x= np.eye(4,4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
# Q1.2: Create an array of 8 zeros using np.zeros()

x= np.zeros(8)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
# Q1.3: Create an array of 6 ones using np.ones()

x= np.ones(6)
print(x)

[1. 1. 1. 1. 1. 1.]


In [6]:
# Q1.4: Create an array with values from 0 to 15 using np.arange()
x= np.arange(0,15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [7]:
# Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()

x= np.linspace(0,100,8)
print(x)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [23]:
# The assignment uses banking industry data with 10 rows × 5 columns:

# Customer_ID: Unique identifier for each customer
# Account_Balance: Customer's account balance in dollars
# Credit_Score: Customer's credit score (300-900 range)
# Transaction_Count: Number of transactions in the last month
# Years_Active: Number of years the customer has been with the bank

banking_data= np.array([[111,2989.5,500,10,5],
                        [222,4000.1,600,6,15],
                        [444,900.9,900,8,5],
                        [333,5000,800,13,18],
                        [777,5848.8,700,25,20],
                        [888,4893.5,850,16,10],
                        [555,6798.2,600,6,17],
                        [000,4886.2,400,10,22],
                        [999,9876.2,500,12,2],
                        [666,3003.6,800,22,30]   
                        ])


np.set_printoptions(suppress=True, precision=2)
print(banking_data)

[[ 111.  2989.5  500.    10.     5. ]
 [ 222.  4000.1  600.     6.    15. ]
 [ 444.   900.9  900.     8.     5. ]
 [ 333.  5000.   800.    13.    18. ]
 [ 777.  5848.8  700.    25.    20. ]
 [ 888.  4893.5  850.    16.    10. ]
 [ 555.  6798.2  600.     6.    17. ]
 [   0.  4886.2  400.    10.    22. ]
 [ 999.  9876.2  500.    12.     2. ]
 [ 666.  3003.6  800.    22.    30. ]]


In [3]:
# Q2.1: What is the shape of the banking_data array?
import numpy as np
banking_data= np.array([[111,2989.5,500,10,5],
                        [222,4000.1,600,6,15],
                        [444,900.9,900,8,5],
                        [333,5000,800,13,18],
                        [777,5848.8,700,25,20],
                        [888,4893.5,850,16,10],
                        [555,6798.2,600,6,17],
                        [000,4886.2,400,10,22],
                        [999,9876.2,500,12,2],
                        [666,3003.6,800,22,30]   
                        ])


np.set_printoptions(suppress=True, precision=2)

print(banking_data.shape)

(10, 5)


In [4]:
# Q2.2: What is the data type of the banking_data array?
banking_data.dtype

dtype('float64')

In [6]:
# Q2.3: What is the size (total number of elements) of the banking_data array?
print(banking_data.size)

50


In [7]:
# Q2.4: What is the number of dimensions of the banking_data array?
print(banking_data.ndim)

2


In [8]:
# Q2.5: What is the memory size of the banking_data array in bytes?
print(banking_data.nbytes)

400


In [10]:
# Q3.1: Extract the first row of banking_data
print(banking_data[0,:])

[ 111.  2989.5  500.    10.     5. ]


In [11]:
# Q3.2: Extract the last row of banking_data
print(banking_data[9,:])

[ 666.  3003.6  800.    22.    30. ]


In [12]:
# Q3.3: Extract the Account_Balance column (column index 1)
print(banking_data[:,1])

[2989.5 4000.1  900.9 5000.  5848.8 4893.5 6798.2 4886.2 9876.2 3003.6]


In [13]:
# Q3.4: Extract the first 4 rows and first 3 columns
print(banking_data[0:4,0:3])

[[ 111.  2989.5  500. ]
 [ 222.  4000.1  600. ]
 [ 444.   900.9  900. ]
 [ 333.  5000.   800. ]]


In [ ]:
# Q3.5: Extract rows 3 to 7 (inclusive)
banking_data= np.array([[111,2989.5,500,10,5],
                        [222,4000.1,600,6,15],
                        [444,900.9,900,8,5],
                        [333,5000,800,13,18],
                        [777,5848.8,700,25,20],
                        [888,4893.5,850,16,10],
                        [555,6798.2,600,6,17],
                        [000,4886.2,400,10,22],
                        [999,9876.2,500,12,2],
                        [666,3003.6,800,22,30]   
                        ])
print(banking_data[2:7,:])

[[ 444.   900.9  900.     8.     5. ]
 [ 333.  5000.   800.    13.    18. ]
 [ 777.  5848.8  700.    25.    20. ]
 [ 888.  4893.5  850.    16.    10. ]
 [ 555.  6798.2  600.     6.    17. ]]


In [16]:
# Q4.1: Calculate the sum of all account balances
x= np.sum(banking_data[:,1])
print(x)

48196.99999999999


In [18]:
# Q4.2: Calculate the mean account balance
x= np.mean(banking_data[:,1])
print(x)

4819.699999999999


In [20]:
# Q4.3: Calculate the standard deviation of account balances
x= np.std(banking_data[:,1])
print(x)

2307.8272669331213


In [22]:
# Q4.4: Calculate the variance of account balances
x= np.var(banking_data[:,1])
print(x)

5326066.694


In [23]:
# Q4.5: Calculate the median account balance
x= np.median(banking_data[:,1])
print(x)

4889.85


In [24]:
# Q5.1: Find the minimum and maximum account balances
x= np.max(banking_data[:,1])
y= np.min(banking_data[:,1])
print(x), print(y)

9876.2
900.9


(None, None)

In [25]:
# Q5.2: Find the minimum and maximum credit scores
x= np.max(banking_data[:,2])
y= np.min(banking_data[:,2])
print(x), print(y)

900.0
400.0


(None, None)

In [28]:
# Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
p25= np.percentile(banking_data[:,1],25)
p50= np.percentile(banking_data[:,1],50)
p75= np.percentile(banking_data[:,1],75)

print(p25), print(p50), print(p75)

3252.725
4889.85
5636.6


(None, None, None)

In [29]:
# Q5.4: Calculate the correlation between account balance and credit score
banking_data= np.array([[111,2989.5,500,10,5],
                        [222,4000.1,600,6,15],
                        [444,900.9,900,8,5],
                        [333,5000,800,13,18],
                        [777,5848.8,700,25,20],
                        [888,4893.5,850,16,10],
                        [555,6798.2,600,6,17],
                        [000,4886.2,400,10,22],
                        [999,9876.2,500,12,2],
                        [666,3003.6,800,22,30]   
                        ])

x= np.corrcoef(banking_data[:,1], banking_data[:,2])[0,1]
print(x)

-0.46128061366331713


In [30]:
# Q5.5: Calculate the covariance between account balance and credit score
x= np.cov(banking_data[:,1],banking_data[:,2])[0,1]
print(x)

-190818.88888888888


In [31]:
print(banking_data)

[[ 111.  2989.5  500.    10.     5. ]
 [ 222.  4000.1  600.     6.    15. ]
 [ 444.   900.9  900.     8.     5. ]
 [ 333.  5000.   800.    13.    18. ]
 [ 777.  5848.8  700.    25.    20. ]
 [ 888.  4893.5  850.    16.    10. ]
 [ 555.  6798.2  600.     6.    17. ]
 [   0.  4886.2  400.    10.    22. ]
 [ 999.  9876.2  500.    12.     2. ]
 [ 666.  3003.6  800.    22.    30. ]]


In [32]:
import numpy as np

# Your banking data
banking_data = np.array([
    [111.,  2989.5, 500., 10., 5.],
    [222.,  4000.1, 600., 6., 15.],
    [444.,   900.9, 900., 8., 5.],
    [333.,  5000.,  800., 13., 18.],
    [777.,  5848.8, 700., 25., 20.],
    [888.,  4893.5, 850., 16., 10.],
    [555.,  6798.2, 600., 6., 17.],
    [0.,    4886.2, 400., 10., 22.],
    [999.,  9876.2, 500., 12., 2.],
    [666.,  3003.6, 800., 22., 30.]
])

# Calculate covariance between account balance (col 1) and credit score (col 2)
covariance = np.cov(banking_data[:, 1], banking_data[:, 2])[0, 1]
print("Covariance between account balance and credit score:", covariance)


Covariance between account balance and credit score: -190818.88888888888


In [33]:
# Q6.1: Reshape the banking_data to 5 rows × 10 columns
x= banking_data.reshape(5,10)
print(x)

[[ 111.  2989.5  500.    10.     5.   222.  4000.1  600.     6.    15. ]
 [ 444.   900.9  900.     8.     5.   333.  5000.   800.    13.    18. ]
 [ 777.  5848.8  700.    25.    20.   888.  4893.5  850.    16.    10. ]
 [ 555.  6798.2  600.     6.    17.     0.  4886.2  400.    10.    22. ]
 [ 999.  9876.2  500.    12.     2.   666.  3003.6  800.    22.    30. ]]


In [34]:
# Q6.2: Flatten the banking_data to a 1D array
print(banking_data.flatten())

[ 111.  2989.5  500.    10.     5.   222.  4000.1  600.     6.    15.
  444.   900.9  900.     8.     5.   333.  5000.   800.    13.    18.
  777.  5848.8  700.    25.    20.   888.  4893.5  850.    16.    10.
  555.  6798.2  600.     6.    17.     0.  4886.2  400.    10.    22.
  999.  9876.2  500.    12.     2.   666.  3003.6  800.    22.    30. ]


In [35]:
# Q6.3: Transpose the banking_data
banking_data.T

array([[ 111. ,  222. ,  444. ,  333. ,  777. ,  888. ,  555. ,    0. ,
         999. ,  666. ],
       [2989.5, 4000.1,  900.9, 5000. , 5848.8, 4893.5, 6798.2, 4886.2,
        9876.2, 3003.6],
       [ 500. ,  600. ,  900. ,  800. ,  700. ,  850. ,  600. ,  400. ,
         500. ,  800. ],
       [  10. ,    6. ,    8. ,   13. ,   25. ,   16. ,    6. ,   10. ,
          12. ,   22. ],
       [   5. ,   15. ,    5. ,   18. ,   20. ,   10. ,   17. ,   22. ,
           2. ,   30. ]])

In [40]:
# Q6.4: Split the banking_data into 2 equal parts vertically
x= np.vsplit(banking_data,2)
print(x)

[array([[ 111. , 2989.5,  500. ,   10. ,    5. ],
       [ 222. , 4000.1,  600. ,    6. ,   15. ],
       [ 444. ,  900.9,  900. ,    8. ,    5. ],
       [ 333. , 5000. ,  800. ,   13. ,   18. ],
       [ 777. , 5848.8,  700. ,   25. ,   20. ]]), array([[ 888. , 4893.5,  850. ,   16. ,   10. ],
       [ 555. , 6798.2,  600. ,    6. ,   17. ],
       [   0. , 4886.2,  400. ,   10. ,   22. ],
       [ 999. , 9876.2,  500. ,   12. ,    2. ],
       [ 666. , 3003.6,  800. ,   22. ,   30. ]])]


In [43]:
# Q6.5: Split the banking_data into 2 equal parts horizontally
x= np.hsplit(banking_data,5)
print(x)

[array([[111.],
       [222.],
       [444.],
       [333.],
       [777.],
       [888.],
       [555.],
       [  0.],
       [999.],
       [666.]]), array([[2989.5],
       [4000.1],
       [ 900.9],
       [5000. ],
       [5848.8],
       [4893.5],
       [6798.2],
       [4886.2],
       [9876.2],
       [3003.6]]), array([[500.],
       [600.],
       [900.],
       [800.],
       [700.],
       [850.],
       [600.],
       [400.],
       [500.],
       [800.]]), array([[10.],
       [ 6.],
       [ 8.],
       [13.],
       [25.],
       [16.],
       [ 6.],
       [10.],
       [12.],
       [22.]]), array([[ 5.],
       [15.],
       [ 5.],
       [18.],
       [20.],
       [10.],
       [17.],
       [22.],
       [ 2.],
       [30.]])]


In [ ]:
print(banking_data)
# Customer_ID: Unique identifier for each customer
# Account_Balance: Customer's account balance in dollars
# Credit_Score: Customer's credit score (300-900 range)
# Transaction_Count: Number of transactions in the last month
# Years_Active: Number of years the customer has been with the bank

[[ 111.  2989.5  500.    10.     5. ]
 [ 222.  4000.1  600.     6.    15. ]
 [ 444.   900.9  900.     8.     5. ]
 [ 333.  5000.   800.    13.    18. ]
 [ 777.  5848.8  700.    25.    20. ]
 [ 888.  4893.5  850.    16.    10. ]
 [ 555.  6798.2  600.     6.    17. ]
 [   0.  4886.2  400.    10.    22. ]
 [ 999.  9876.2  500.    12.     2. ]
 [ 666.  3003.6  800.    22.    30. ]]


In [50]:
# Q7.1: Find customers with account balance greater than $100,000
x=(banking_data[:,1]>100000)
print(banking_data[x])

[]


In [58]:
# Q7.2: Find customers with credit score greater than 800
Customer_ID= banking_data[:,0]
x= Customer_ID[banking_data[:,2]>800]
print(x)

[444. 888.]


In [57]:
# Extract customer IDs from column 0
Customer_ID = banking_data[:, 0]

# Get IDs of customers with credit score > 800 (from column 2)
x = Customer_ID[banking_data[:, 2] > 800]
print("Customer IDs with credit score > 800:", x)

Customer IDs with credit score > 800: [444. 888.]


In [ ]:

print(banking_data)
# Customer_ID: Unique identifier for each customer
# Account_Balance: Customer's account balance in dollars
# Credit_Score: Customer's credit score (300-900 range)
# Transaction_Count: Number of transactions in the last month
# Years_Active: Number of years the customer has been with the bank


[[ 111.  2989.5  500.    10.     5. ]
 [ 222.  4000.1  600.     6.    15. ]
 [ 444.   900.9  900.     8.     5. ]
 [ 333.  5000.   800.    13.    18. ]
 [ 777.  5848.8  700.    25.    20. ]
 [ 888.  4893.5  850.    16.    10. ]
 [ 555.  6798.2  600.     6.    17. ]
 [   0.  4886.2  400.    10.    22. ]
 [ 999.  9876.2  500.    12.     2. ]
 [ 666.  3003.6  800.    22.    30. ]]


In [65]:
# Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750
Transaction_Count=banking_data[:,3]
Credit_Score=banking_data[:,2]
Customers_ID=banking_data[:,0]
x= banking_data[(banking_data[:,3]>50) & (banking_data[:,2]<750)]
print(x)

[]


In [63]:
# Q7.4: Count how many customers have account balance between $10,000 and $100,000
count= np.sum((banking_data[:,1]>10000) & (banking_data[:,1]<100000))
print(count)

0


In [69]:
# Q7.5: Find the index of the customer with the highest credit score
x= np.argmax(banking_data[:,2])
print(x)

2


In [76]:
# Q8.1: Sort the banking_data by account balance (ascending)

x= banking_data[banking_data[:,1].argsort()]
print(x)

[[ 444.   900.9  900.     8.     5. ]
 [ 111.  2989.5  500.    10.     5. ]
 [ 666.  3003.6  800.    22.    30. ]
 [ 222.  4000.1  600.     6.    15. ]
 [   0.  4886.2  400.    10.    22. ]
 [ 888.  4893.5  850.    16.    10. ]
 [ 333.  5000.   800.    13.    18. ]
 [ 777.  5848.8  700.    25.    20. ]
 [ 555.  6798.2  600.     6.    17. ]
 [ 999.  9876.2  500.    12.     2. ]]


In [79]:
# Q8.2: Sort the banking_data by credit score (descending)

x= banking_data[banking_data[:,2].argsort()[::-1]]
print(x)

[[ 444.   900.9  900.     8.     5. ]
 [ 888.  4893.5  850.    16.    10. ]
 [ 333.  5000.   800.    13.    18. ]
 [ 666.  3003.6  800.    22.    30. ]
 [ 777.  5848.8  700.    25.    20. ]
 [ 222.  4000.1  600.     6.    15. ]
 [ 555.  6798.2  600.     6.    17. ]
 [ 999.  9876.2  500.    12.     2. ]
 [ 111.  2989.5  500.    10.     5. ]
 [   0.  4886.2  400.    10.    22. ]]


In [81]:
# Q8.3: Find the indices that would sort the array by years active
years_active= [banking_data[:,4].argsort()]
print(years_active)

[array([8, 0, 2, 5, 1, 6, 3, 4, 7, 9])]


In [90]:
# Q8.4: Find the customer with the second highest account balance

x=banking_data[:,1].argsort()[::-1][1]
print(x)


6


In [ ]:
print(banking_data)

[[ 111.  2989.5  500.    10.     5. ]
 [ 222.  4000.1  600.     6.    15. ]
 [ 444.   900.9  900.     8.     5. ]
 [ 333.  5000.   800.    13.    18. ]
 [ 777.  5848.8  700.    25.    20. ]
 [ 888.  4893.5  850.    16.    10. ]
 [ 555.  6798.2  600.     6.    17. ]
 [   0.  4886.2  400.    10.    22. ]
 [ 999.  9876.2  500.    12.     2. ]
 [ 666.  3003.6  800.    22.    30. ]]


In [100]:
# Q8.5: Find the customer with the lowest transaction count
x= banking_data[banking_data[:,4].min]
print(x)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices