In [4]:
retail_data= [[    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25],
       [   10, 33000,   410,  1450,    11]]

In [5]:
print(retail_data)

[[1, 25000, 300, 1200, 10], [2, 32000, 450, 1500, 15], [3, 28000, 380, 1100, 8], [4, 41000, 500, 1600, 20], [5, 35000, 420, 1400, 12], [6, 27000, 360, 1300, 9], [7, 39000, 480, 1700, 18], [8, 30000, 400, 1250, 14], [9, 45000, 550, 1800, 25], [10, 33000, 410, 1450, 11]]


In [7]:
import numpy as np
retail_data= np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]])

print(retail_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [9]:
#[Store ID, Sales, Customers, Inventory, Returns]
#1. What is the **total revenue** generated across all stores?

retail_data[: ,1].sum()

np.int64(335000)

In [11]:
#2. Which store recorded the **highest sales**?

retail_data[:,1].argmax()+1

np.int64(9)

In [12]:
#3. Which store recorded the **lowest sales**?

retail_data[:,1].argmin()+1

np.int64(1)

In [13]:
#4. What is the **average daily sales** per store?

retail_data[:,1]/10

array([2500., 3200., 2800., 4100., 3500., 2700., 3900., 3000., 4500.,
       3300.])

In [ ]:
#5. How many stores achieved sales **above ₹35,000**?

sales= retail_data[:,1]
sum(sales>35000)


np.int64(3)

In [ ]:
#6. Which store had the **highest customer footfall**?
#   [1, 25000, 300, 1200, 10],
#     [2, 32000, 450, 1500, 15],
#     [3, 28000, 380, 1100, 8],
#     [4, 41000, 500, 1600, 20],
#     [5, 35000, 420, 1400, 12],
#     [6, 27000, 360, 1300, 9],
#     [7, 39000, 480, 1700, 18],
#     [8, 30000, 400, 1250, 14],
#     [9, 45000, 550, 1800, 25],
#     [10, 33000, 410, 1450, 11]
##[Store ID, Sales, Customers, Inventory, Returns]

retail_data[:,2].max()

np.int64(550)

In [22]:
#7. What is the **average number of customers** per store?

retail_data[:,2]/10

array([30., 45., 38., 50., 42., 36., 48., 40., 55., 41.])

In [30]:
#8. How many stores have **more than 450 customers**?

customers= retail_data[:,2]
sum(customers>450)

np.int64(3)

In [31]:
#9. Which store has the **lowest customer count**?
retail_data[:,2].argmin()+1

np.int64(1)

In [ ]:
#10. Is there any store where **high sales do not correspond to high customers**?
#   [1, 25000, 300, 1200, 10],
#     [2, 32000, 450, 1500, 15],
#     [3, 28000, 380, 1100, 8],
#     [4, 41000, 500, 1600, 20],
#     [5, 35000, 420, 1400, 12],
#     [6, 27000, 360, 1300, 9],
#     [7, 39000, 480, 1700, 18],
#     [8, 30000, 400, 1250, 14],
#     [9, 45000, 550, 1800, 25],
#     [10, 33000, 410, 1450, 11]
##[Store ID, Sales, Customers, Inventory, Returns]

In [32]:
#11. What is the **total inventory** across all stores?
retail_data[:,3].sum()

np.int64(14300)

In [34]:
#12. Which store has the **highest inventory stock**?
retail_data[:,3].argmax()+1

np.int64(9)

In [36]:
#13. How many stores have **inventory less than 1300 units**?
sum(retail_data[:,3]<1300)

np.int64(3)

In [47]:
#14. Which store has the **highest return rate** (returns ÷ inventory)?
#   [1, 25000, 300, 1200, 10],
#     [2, 32000, 450, 1500, 15],
#     [3, 28000, 380, 1100, 8],
#     [4, 41000, 500, 1600, 20],
#     [5, 35000, 420, 1400, 12],
#     [6, 27000, 360, 1300, 9],
#     [7, 39000, 480, 1700, 18],
#     [8, 30000, 400, 1250, 14],
#     [9, 45000, 550, 1800, 25],
#     [10, 33000, 410, 1450, 11]
##[Store ID, Sales, Customers, Inventory, Returns]
(retail_data[:,4]/retail_data[:,3]).argmax()+1


np.int64(9)

In [49]:
#15. Which stores have **returns greater than 15 units**?
sum(retail_data[:,4]>15)

np.int64(3)

In [5]:
import numpy as np
retail_data= np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]])

print(retail_data)


#19. How many stores have **sales per customer above ₹90**?

sum((retail_data[:,1]/retail_data[:,2])>90)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


np.int64(0)

In [ ]:

##[Store ID, Sales, Customers, Inventory, Returns]

#
