In [6]:
# NumPy Assignment
# QUESTION 1: ARRAY CREATION AND MANIPULATION

print("\nQ1.1: Create a 3x3 identity matrix using np.eye()")
import numpy as np
a= np.eye(3,3)
print(a)


Q1.1: Create a 3x3 identity matrix using np.eye()
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
print("\nQ1.2: Create an array of 10 zeros using np.zeros()")

a= np.zeros(10)
print(a)


Q1.2: Create an array of 10 zeros using np.zeros()
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
print("\nQ1.3: Create an array of 5 ones using np.ones()")

a= np.ones(5)
print(a)


Q1.3: Create an array of 5 ones using np.ones()
[1. 1. 1. 1. 1.]


In [15]:
print("\nQ1.4: Create an array with values from 0 to 9 using np.arange()")

a= np.arange(0,10)
print(a)


Q1.4: Create an array with values from 0 to 9 using np.arange()
[0 1 2 3 4 5 6 7 8 9]


In [18]:
print("\nQ1.5: Create an array with 6 evenly spaced values from 0 to 10 using np.linspace()")

a= np.linspace(0,10,6)
a


Q1.5: Create an array with 6 evenly spaced values from 0 to 10 using np.linspace()


array([ 0.,  2.,  4.,  6.,  8., 10.])

In [19]:
# QUESTION 2: ARRAY ATTRIBUTES AND INFORMATION

retail_data = np.array([
    [1001, 29.99, 45, 4.2, 15],
    [1002, 49.99, 32, 4.5, 8],
    [1003, 19.99, 78, 3.8, 22],
    [1004, 89.99, 12, 4.7, 5],
    [1005, 15.99, 95, 4.0, 18],
    [1006, 69.99, 28, 4.3, 12],
    [1007, 39.99, 56, 3.9, 20],
    [1008, 79.99, 18, 4.6, 7],
    [1009, 25.99, 67, 4.1, 16],
    [1010, 59.99, 34, 4.4, 10]
])
# Columns: Product_ID, Price, Quantity_Sold, Customer_Rating, Days_in_Stock

print("\nQ2.1: What is the shape of the retail_data array?")

print(retail_data.shape)


Q2.1: What is the shape of the retail_data array?
(10, 5)


In [20]:
print("\nQ2.2: What is the data type of the retail_data array?")

print(retail_data.dtype)


Q2.2: What is the data type of the retail_data array?
float64


In [21]:
print("\nQ2.3: What is the size (total number of elements) of the retail_data array?")

x= retail_data.size
print(x)


Q2.3: What is the size (total number of elements) of the retail_data array?
50


In [22]:
print("\nQ2.4: What is the number of dimensions of the retail_data array?")

x= retail_data.ndim
print(x)


Q2.4: What is the number of dimensions of the retail_data array?
2


In [24]:
print("\nQ2.5: What is the memory size of the retail_data array in bytes?")

x= retail_data.nbytes
print(x)


Q2.5: What is the memory size of the retail_data array in bytes?
400


In [35]:
x=np.random.randint(0,10,size=10)
print(x)
print(x.size)
print(x.nbytes)

[5 8 1 7 1 3 9 6 7 9]
10
40


In [36]:
# QUESTION 3: INDEXING AND SLICING
retail_data = np.array([
    [1001, 29.99, 45, 4.2, 15],
    [1002, 49.99, 32, 4.5, 8],
    [1003, 19.99, 78, 3.8, 22],
    [1004, 89.99, 12, 4.7, 5],
    [1005, 15.99, 95, 4.0, 18],
    [1006, 69.99, 28, 4.3, 12],
    [1007, 39.99, 56, 3.9, 20],
    [1008, 79.99, 18, 4.6, 7],
    [1009, 25.99, 67, 4.1, 16],
    [1010, 59.99, 34, 4.4, 10]
])
# Columns: Product_ID, Price, Quantity_Sold, Customer_Rating, Days_in_Stock

print("\nQ3.1: Extract the first row of retail_data")

print(retail_data[0,:])


Q3.1: Extract the first row of retail_data
[1001.     29.99   45.      4.2    15.  ]


In [37]:
print("\nQ3.2: Extract the last row of retail_data")

retail_data[9]


Q3.2: Extract the last row of retail_data


array([1010.  ,   59.99,   34.  ,    4.4 ,   10.  ])

In [38]:
print("\nQ3.3: Extract the Price column (column index 1)")
retail_data[:,1]


Q3.3: Extract the Price column (column index 1)


array([29.99, 49.99, 19.99, 89.99, 15.99, 69.99, 39.99, 79.99, 25.99,
       59.99])

In [39]:
retail_data = np.array([
    [1001, 29.99, 45, 4.2, 15],
    [1002, 49.99, 32, 4.5, 8],
    [1003, 19.99, 78, 3.8, 22],
    [1004, 89.99, 12, 4.7, 5],
    [1005, 15.99, 95, 4.0, 18],
    [1006, 69.99, 28, 4.3, 12],
    [1007, 39.99, 56, 3.9, 20],
    [1008, 79.99, 18, 4.6, 7],
    [1009, 25.99, 67, 4.1, 16],
    [1010, 59.99, 34, 4.4, 10]
])
# Columns: Product_ID, Price, Quantity_Sold, Customer_Rating, Days_in_Stock
print("\nQ3.4: Extract the first 3 rows and first 2 columns")

retail_data[0:3,0:2]


Q3.4: Extract the first 3 rows and first 2 columns


array([[1001.  ,   29.99],
       [1002.  ,   49.99],
       [1003.  ,   19.99]])

In [40]:
print("\nQ3.5: Extract rows 2 to 5 (inclusive)")
retail_data[2:6]


Q3.5: Extract rows 2 to 5 (inclusive)


array([[1003.  ,   19.99,   78.  ,    3.8 ,   22.  ],
       [1004.  ,   89.99,   12.  ,    4.7 ,    5.  ],
       [1005.  ,   15.99,   95.  ,    4.  ,   18.  ],
       [1006.  ,   69.99,   28.  ,    4.3 ,   12.  ]])

In [42]:
# QUESTION 4: MATHEMATICAL OPERATIONS
retail_data = np.array([
    [1001, 29.99, 45, 4.2, 15],
    [1002, 49.99, 32, 4.5, 8],
    [1003, 19.99, 78, 3.8, 22],
    [1004, 89.99, 12, 4.7, 5],
    [1005, 15.99, 95, 4.0, 18],
    [1006, 69.99, 28, 4.3, 12],
    [1007, 39.99, 56, 3.9, 20],
    [1008, 79.99, 18, 4.6, 7],
    [1009, 25.99, 67, 4.1, 16],
    [1010, 59.99, 34, 4.4, 10]
])
# Columns: Product_ID, Price, Quantity_Sold, Customer_Rating, Days_in_Stock
print("\nQ4.1: Calculate the sum of all prices")
retail_data[:,1].sum()



Q4.1: Calculate the sum of all prices


np.float64(481.9)

In [43]:
print("\nQ4.2: Calculate the mean price")
retail_data[:,1].mean()


Q4.2: Calculate the mean price


np.float64(48.19)

In [44]:
print("\nQ4.3: Calculate the standard deviation of prices")
retail_data[:,1].std()


Q4.3: Calculate the standard deviation of prices


np.float64(24.697368280851297)

In [46]:
print("\nQ4.4: Calculate the variance of prices")
retail_data[:,1].var()


Q4.4: Calculate the variance of prices


np.float64(609.9599999999998)

In [47]:
print("\nQ4.5: Calculate the median price")
x= np.median(retail_data[:,1])
print(x)


Q4.5: Calculate the median price
44.99


In [49]:
print("\nQ5.1: Find the minimum and maximum prices")
retail_data = np.array([
    [1001, 29.99, 45, 4.2, 15],
    [1002, 49.99, 32, 4.5, 8],
    [1003, 19.99, 78, 3.8, 22],
    [1004, 89.99, 12, 4.7, 5],
    [1005, 15.99, 95, 4.0, 18],
    [1006, 69.99, 28, 4.3, 12],
    [1007, 39.99, 56, 3.9, 20],
    [1008, 79.99, 18, 4.6, 7],
    [1009, 25.99, 67, 4.1, 16],
    [1010, 59.99, 34, 4.4, 10]
])
# Columns: Product_ID, Price, Quantity_Sold, Customer_Rating, Days_in_Stock
x= retail_data[:,1].max()
print(x)
y= retail_data[:,1].min()
print(y)


Q5.1: Find the minimum and maximum prices
89.99
15.99


In [52]:
print("\nQ5.2: Find the minimum and maximum quantities sold")
x= retail_data[:,2].max()
print(x)
y= retail_data[:,2].min()
print(y)


Q5.2: Find the minimum and maximum quantities sold
95.0
12.0


In [ ]:
print("\nQ5.3: Calculate the percentile values for prices (25th, 50th, 75th)")